spring:
  config:
    import: "configserver:http://localhost:18080"
  application:
    name: notification
  profiles:
    active: dev

  kafka:
    bootstrap-servers: localhost:9092  # 카프카 브로커 URL
    consumer:
      group-id: notification-group  # 소비자 그룹 ID (필요에 따라 설정)
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

message: "default message" # config server를 통과하지 않을 때

management:
  endpoint:
    prometheus:
      access: unrestricted
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: [health, info, prometheus]

  prometheus:
    metrics.export.enabled: true

  metrics:
    # ✨ 추가: 모든 메트릭에 자동으로 태그를 붙여줌
    # Grafana에서 여러 서비스를 구분할 때 유용
    tags:
      application: notification-service  # 서비스 이름 태그
      env: dev                          # 환경 태그 (dev/prod)

    distribution:
      # 1) 히스토그램
      percentiles-histogram:
        "[http.server.requests]": true        # 대괄호 → IDE 경고 X
      # 2) 퍼센타일
      percentiles:
        "[http.server.requests]": 0.95,0.99
      # 3) SLO 버킷
      slo:
        "[http.server.requests]": 100ms,300ms,500ms,1s,3s



# 카프카 설정 추가


#spring:
#  profiles:
#    active: prod
#  cloud:
#    config:
#      enabled: false