rule_files:
  - "/etc/prometheus/rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: 'payment-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:19080']

  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:19030']

  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:19110']

  - job_name: 'coupon-server'
    honor_labels: true
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:19100']
        labels:
          env: prod
          application: coupon

  - job_name: 'host' # 컨테이너/호스트 머신의 시스템 리소스 상태를 Prometheus로 수집
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          env: prod

  - job_name: 'kafka-exporter'  # Kafka 브로커/토픽/컨슈머 그룹 상태를 Prometheus로 수집
    static_configs:
      - targets: ['kafka-exporter:9308']
        labels:
          env: prod