server:
  port: 19100

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

spring:
  jpa:
    hibernate:
      ddl-auto: validate           # 스키마 누락 시 즉시 실패(권장)
    properties:
      hibernate:
        show_sql: false # 임시
        format_sql: false # 임시
        use_sql_comments: true
        default_schema: coupons
        generate_statistics: false # 임시
  datasource:
    url: jdbc:postgresql://localhost:5432/livecommerce
    username: postgres
    password: 8dostore
    driver-class-name: org.postgresql.Driver
    hikari:
      data-source-properties:
        currentSchema: "coupons,public"  # PG JDBC -> search_path 설정
  cache:
    type: redis
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}



  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      # 전용 매핑
      acks: all
      retries: 10
      batch-size: 32768

      # 네이티브 프로듀서/시리얼라이저 속성
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 1
        delivery.timeout.ms: 120000
        linger.ms: 10
        spring.json.add.type.headers: true
        spring.json.type.mapping: >
          coupon-used: com.live_commerce.coupon.infrastructure.kafka.message.CouponUsedMessage

    consumer:
      group-id: coupon # 이게 빠졌었네;;
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.live_commerce.*
        spring.json.type.mapping: >
          first-join-coupon: com.live_commerce.coupon.infrastructure.kafka.event.FirstJoinCouponEvent,
          coupon-used:com.live_commerce.coupon.domain.event.CouponUsedEvent

    listener:
      ack-mode: MANUAL_IMMEDIATE # 수동 ack 처리 모드 설정

logging:
  level:
    # 애플리케이션 기본
    root: INFO
    # 하이버네이트 SQL/바인딩 노이즈 억제
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN
    org.hibernate.type.descriptor.sql: WARN
    org.springframework.security: DEBUG
    # 카프카 클라이언트 노이즈 억제
    org.apache.kafka: WARN
    # 스케줄러/릴레이와 컨슈머는 운영 시 INFO, 대량이면 DEBUG로 내림
    com.lc.coupon.application.relay: INFO
    com.lc.coupon.infra.kafka.consumer: INFO

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
gateway:
  base-url: http://localhost:19091

springdoc:
  api-docs:
    path: /v3/api-docs/coupon

coupon:
  topics:
    coupon-used: coupons.CouponUsed.v1 # 쿠폰 사용 Kafka 토픽 설정
  outbox:
    enabled: true # Outbox 모드 활성화 (true: Outbox 모드, false: 직발행 모드)

