server:
  port: 19100

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

spring:
  application:
    name: coupon
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_schema: coupons
  datasource:
    url: jdbc:postgresql://localhost:5432/livecommerce
    username: postgres
    password: 8dostore
    driver-class-name: org.postgresql.Driver

  cache:
    type: redis
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
         spring.json.add.type.headers: true
         spring.json.type.mapping: >
           coupon-used: com.live_commerce.coupon.infrastructure.kafka.message.CouponUsedMessage
#     여기 아래 설정들은 뭐지??
      acks: all
      retries: 10
      enable.idempotence: true
      delivery.timeout.ms: 120000
      linger.ms: 10
      batch.size: 32768

    consumer:
      group-id: ${spring.application.name}m
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.live_commerce.*
#        com.live_commerce.user.infrastructure.kafka.event, com.live_commerce.coupon.infrastructure.kafka.event
        spring.json.type.mapping: >
          first-join-coupon: com.live_commerce.coupon.infrastructure.kafka.event.FirstJoinCouponEvent,
          coupon-used:com.live_commerce.coupon.domain.event.CouponUsedEvent

    listener:
      ack-mode: MANUAL_IMMEDIATE

gateway:
  base-url: http://localhost:19091

springdoc:
  api-docs:
    path: /v3/api-docs/coupon

coupon:
  topics:
    coupon-used: coupons.CouponUsed.v1