server:
  port: 19100

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

spring:
  application:
    name: coupon
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_schema: coupons
  datasource:
    url: jdbc:postgresql://localhost:5432/livecommerce
    username: postgres
    password: 8dostore
    driver-class-name: org.postgresql.Driver

  cache:
    type: redis
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      # 전용 매핑
      acks: all                # 멱등성 / 모든 복제본 ack 후 성공 처리
      retries: 10
      batch-size: 32768        # 전용 매핑 사용 (또는 properties.batch.size 로 대체 가능)

      # 네이티브 프로듀서/시리얼라이저 속성
      properties:
        enable.idempotence: true                   # 멱등성 / 중복 전송 방지
        max.in.flight.requests.per.connection: 1   # 멱등성 / 순서 보장
        delivery.timeout.ms: 120000                # 전송 최대 대기 시간
        linger.ms: 10                              # 최대 10ms 모아 배치 전송 (처리량↑, 지연↑)
        spring.json.add.type.headers: true
        spring.json.type.mapping: >
          coupon-used: com.live_commerce.coupon.infrastructure.kafka.message.CouponUsedMessage

    consumer:
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.live_commerce.*
#        com.live_commerce.user.infrastructure.kafka.event, com.live_commerce.coupon.infrastructure.kafka.event
        spring.json.type.mapping: >
          first-join-coupon: com.live_commerce.coupon.infrastructure.kafka.event.FirstJoinCouponEvent,
          coupon-used:com.live_commerce.coupon.domain.event.CouponUsedEvent

    listener:
      ack-mode: MANUAL_IMMEDIATE # 수동 ack 처리 모드 설정

gateway:
  base-url: http://localhost:19091

springdoc:
  api-docs:
    path: /v3/api-docs/coupon

coupon:
  topics:
    coupon-used: coupons.CouponUsed.v1 # 쿠폰 사용 Kafka 토픽 설정
  outbox:
    enabled: true # Outbox 모드 활성화 (true: Outbox 모드, false: 직발행 모드)