server:
  port: 19110

spring:
  application:
    name: notification
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_schema: notifications
  datasource:
    url: jdbc:postgresql://localhost:5432/livecommerce
    username: postgres
    password: 8dostore
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: >
          notification-created: com.live_commerce.notification.infrastructure.kafka.event.NotificationCreatedEvent
    consumer:
      group-id: ${spring.application.name}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.live_commerce.notification.infrastructure.kafka.event
        spring.json.type.mapping: >
          notification-created: com.live_commerce.notification.infrastructure.kafka.event.NotificationCreatedEvent
    listener:
      ack-mode: MANUAL_IMMEDIATE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,refresh
#  endpoint:
#    prometheus:
#      enabled: true
  metrics:
    tags:
      application: notification-service

gateway:
  base-url: http://localhost:19091

springdoc:
  api-docs:
    path: /v3/api-docs/notification