spring:
  config:
    import: "configserver:http://localhost:18080"
  application:
    name: coupon
  profiles:
    active: dev
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.kafka.listener: INFO
    org.springframework.kafka.KafkaListenerEndpointContainer: INFO
#spring:
#  profiles:
#    active: prod
#  cloud:
#    config:
#      enabled: false